<a href="{{ url('dashboardView') }}">Reporte de ventas y compras</a>
<a href="{{ url('category') }}">Categorías</a>
<a href="{{ url('item') }}">Productos</a>
<a href="{{ url('sale') }}">Ventas</a>
<a href="{{ url('entry') }}">Compras</a>
<a href="{{ url('provider') }}">Proveedores</a>
<a href="{{ url('client') }}">Clientes</a>
<a href="{{ url('rol') }}">Roles</a>
<a href="{{ url('user') }}">Gestión de usuarios</a>